# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dataKaryawan' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dataKaryawan
pod ‘Alamofire’
pod ’SwiftyJSON’

  target 'dataKaryawanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dataKaryawanUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
